# basic options
title: Your awesome title
author: Oluwaseun Awotodunbo
email: nuesleinad@hotmail.com
description: Test Blog
twitter_username: update1
github_username: update2

# Build settings
markdown: kramdown
theme: minima
